version: "3"

services:
  scrape-calendar-data:
    image: ghsapp/scrape-calendar-data
    network_mode: "host"
    volumes:
      - ~/secrets/firestore_creds.json:/src/
  server-monitor:
    build: Server-Monitor
    network_mode: "host"
    restart: on-failure
