version: "3"

services:
  scrape-calendar-data:
    image: ghsapp/scrape-calendar-data
    network_mode: "host"
    volumes:
      - ~/secrets:/src/
  server-monitor:
    image: ghsapp/server-monitor
    network_mode: "host"
    restart: on-failure
    volumes:
      - ~/secrets:/src/
