version: "3"

services:
  scrape-calendar-data:
    image: ghsapp/scrape-calendar-data
    network_mode: "host"
    volumes:
      - ~/secrets:/src/
  server-monitor:
    image: ghsapp/server-monitor
  status-lights:
    container_name: status-lights
    image: ghsapp/status-lights
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - ~/secrets:/src
