version: "3"


services:
  scrape-calendar-data:
    build: Scrape-Calendar-Data
    network_mode: "host"
  server-monitor:
    build: Server-Monitor
    restart: unless-stopped
    network_mode: "host"
  status-lights:
    build: Status-Lights
    network_mode: "host"
    devices: 
      - /dev/gpiomem:/dev/gpiomem
